version: '3.8'

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:14
    container_name: event-organizer-postgres
    environment:
      POSTGRES_DB: event_organizer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Backend на Java Spring Boot
  backend:
    build: ./backend
    container_name: event-organizer-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/event_organizer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

  # Frontend на React
  frontend:
    build: ./frontend
    container_name: event-organizer-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 